name: Reporting

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
         python-version: 3.11

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest
          playwright install

      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.zip
          sudo apt-get update
          sudo apt-get install unzip -y
          unzip allure-2.29.0.zip -d /opt/allure
          sudo ln -s /opt/allure/allure-2.29.0/bin/allure /usr/bin/allure
          allure --version

      - name: Run tests
        run: |
          mkdir -p test-artifacts
          pytest --tracing=on --output "test-artifacts" --screenshot=on --output "test-artifacts" --video=on --output "test-artifacts" --junitxml=test-artifacts/junit.xml --html=test-artifacts/report.html --self-contained-html --alluredir=allure-results

      - name: Generate Allure HTML report
        run: |
          allure generate allure-results -o test-artifacts/allure-report --clean


      - name: Upload Artifacts
        if: always()   # even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: TEST ARTIFACTS

          path: |
            test-artifacts/allure-report
            test-artifacts/junit.xml
            test-artifacts/report.html
            test-artifacts/**


#      - name: Upload junit
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#          name: junit
#          path:

#      - name: Upload html
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#          name: html-report
#          path: report/report.html

#      - name: Upload traces/screenshots
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#          name: traces
#          path: test-artifacts/**


